# Generated by Django 3.0.5 on 2020-05-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_log', '0002_topic_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
