# Generated by Django 3.0.7 on 2020-12-14 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_log', '0003_topic_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-date_added'], 'verbose_name_plural': 'entries'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-date_added']},
        ),
    ]
